---
- hosts: localhost
  become: yes
  tasks:
  - name: add repo
    apt_repository: 
      repo: ppa:openjdk-r/ppa    
  - name: install openjdk-8
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present 
  - name: Ensure group "tomcat" exists
    group:
      name: tomcat 
      state: present 
  - name: Add the user 'tomcat' with a specific uid and a primary group of 'tomcat'
    user:
      name: tomcat 
      comment: tomcat done
      group: tomcat
  - name: Download apache-tomcat-8.5.40.tar.gz
    get_url:
      url: https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
      dest: /tmp/  
  - name: create a directory tomcat if not exists
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
  - name: Extract archive
    unarchive:
      src: /tmp/apache-tomcat-8.5.40.tar.gz
      dest: /opt/tomcat                             
      extra_opts: [--strip-components=1]
      remote_src: yes
  - name: change th directory to /opt/tomcat
    shell: cd /opt/tomcat
  - name: Change ownership of Tomcat installation
    file: 
      path: /opt/tomcat
      owner: tomcat 
      group: tomcat 
      state: directory 
      recurse: yes
  - name: Configure Tomcat server
    template: 
      src: tomcat-server.xml.j2 
      dest: /etc/systemd/system/tomcat.service
    notify: 
    - tomcat-8-restart
  - name: Configure Tomcat users
    template: 
      src: tomcat-users.xml.j2 
      dest: /opt/tomcat/conf/tomcat-users.xml
      mode: 0755
      remote_src: yes
    notify: 
    - tomcat-8-restart
  - name: configure Manager
    template: 
      src: context.xml.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml
  - name: configure Host-Manager
    template: 
      src: context.xml.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
  - name: Download gameoflife.war file
    get_url:
      url: https://s3.amazonaws.com/gameoflife-war-file/gameoflife.war
      dest: /tmp/ 
  - name: move the war file from /tmp to webaps path
    shell: mv /tmp/gameoflife.war /opt/tomcat/webapps/
  - name: changing permisssions for webapps 
    shell: chmod 755 /opt/tomcat/webapps/gameoflife.war
    notify: 
    - tomcat-8-restart
  handlers:
    - name: tomcat-8-restart
      service: 
        name: tomcat 
        state: restarted
        
